workflows:
  ios-cache-workflow:
    name: iOS HomeTask
    environment:
      xcode: latest # <-- set to specific version e.g. 14.3, 15.0 to avoid unexpected updates.
      vars:
        XCODE_PROJECT: "HomeTask.xcodeproj"
        XCODE_SCHEME: "HomeTask"
    scripts:
      - name: Build ipa for development
        script: |
          xcodebuild build -project "$XCODE_PROJECT" -scheme "$XCODE_SCHEME" CODE_SIGN_INDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
