workflows:
  ios-cache-workflow:
    name: iOS HomeTask
    integrations:
      app_store_connect: Codemagic
    environment:
      groups:
      - firebase_credentials
      xcode: latest
      ios_signing:
        distribution_type: ad_hoc # or: ad_hoc | development | enterprise
        bundle_identifier: com.onflyer.HomeTask
      vars:
        BUNDLE_ID: "com.onflyer.HomeTask" # replace with your app bundle
        XCODE_PROJECT: "HomeTask.xcodeproj"
        XCODE_SCHEME: "HomeTask"
    scripts:
      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles
      - name: Build debug app
        script: |
          xcodebuild build -project "$XCODE_PROJECT" \
          -scheme "$XCODE_SCHEME" \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa \
            --project "$CM_BUILD_DIR/$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      firebase:
        firebase_service_account: $FIREBASE_SERVICE_ACCOUNT
        ios:
          app_id: 1:759744663254:ios:0b46f176968f67461d0377
          groups:
            - iosTesters
    
